# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo_position',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Posição da foto'),
        ),
    ]
